import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  if (isLoading) {
    return (
      <main className="h-screen flex justify-center">
        <p>Loading...</p>
      </main>
    );
  }

  if (!data) {
    return (
      <main className="h-screen flex justify-center">
        <p>No data found. Maybe something went wrong?</p>
      </main>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center">
        <div className="w-full h-full border-x border-slate-400 md:max-w-2xl p-2">
          <div className="flex border-b border-slate-400 p-4">
            <h1 className="text-2xl italic">SwagJack</h1>
            <span className="ml-auto">
              {!user.isSignedIn && <SignInButton />}
              {!!user.isSignedIn && <SignOutButton />}
            </span>
          </div>
          <div className="flex flex-col">
            {data?.map((post) => {
              return (
                <div className="border-b border-slate-400 p-8" key={post.id}>
                  <p>{post.content}</p>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
