import Head from "next/head";
import { useRouter } from "next/router";

export default function Post() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>ChirpChirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center">
        <div className="w-full h-full border-x border-slate-400 md:max-w-2xl p-2">
          <div>Show post with id {router.query.id}</div>
        </div>
      </main>
    </>
  );
}
